import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/navbar";
import LoadingProgressBar from "@/component/common/LoadingProgressBar";
import { UserContextProvider } from "./userContext";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Malek Daily Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.boxicons.com/fonts/basic/boxicons.min.css"
          rel="stylesheet"
        />
        <link href="/web-icon-01.png" rel="icon" />
      </head>
      <body className={inter.className}>
        <LoadingProgressBar />
        <Navbar />
        <UserContextProvider>
          {children}
          <ToastContainer position="top-center" />
        </UserContextProvider>
      </body>
    </html>
  );
}
